
- hosts: ansible-host-grp

  gather_facts: yes
  become: true
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
  - name: Install python, nano, curl
    apt:
      update_cache: yes
      state: latest
      name: "{{ item }}"
    with_items:
     - python3
     - nano
     - curl
     - wget
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
